### ISSUE TITLE
Error occurs when execute "yo hubot"

### ISSUE THREAD

**Issue by xiakunhou** [github/generator-hubot#1]
I have install "generator-hubot", when execute command "yo hubot", there is an error,
Error hubot

You don't seem to have a generator with the name hubot installed.
You can see available generators with npm search yeoman-generator and then insta
ll them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.

**Comment by yogiben** [comment]
@technicalpickles I still had this error

I tried `npm install -g hubot coffee-script yo generator-hubot` 

with different versions of node & npm, uninstalling and reinstalling components.

After 30 mins of fiddling, this worked:
`npm install https://github.com/github/generator-hubot/archive/master.tar.gz`
