### ISSUE TITLE
`npm install -g coffee-script` is necessary?

### ISSUE THREAD

**Issue by bouzuya** [github/generator-hubot#22]
`npm install -g coffee-script`. Is it necessary?

`npm test` does not work unless install coffee-script. I fixed it. See #11 .

**Comment by technicalpickles** [comment]
I'm not sure what you are referring to. Where are you seeing to do `npm install -g coffee-script`?

**Comment by technicalpickles** [comment]
Oh, I see what you mean now. No, it shouldn't be necessary and is fixed by https://github.com/github/generator-hubot/pull/28
