### ISSUE TITLE
Include better test examples

### ISSUE THREAD

**Issue by technicalpickles** [github/generator-hubot#45]
If you look at https://github.com/github/generator-hubot/blob/master/generators/script/templates/test/template-test.coffee the tests are super week. They only verify that listeners have been registered with specific regexes, which isn't very helpful functionally.

[hubot-mock-adapter](https://www.npmjs.com/package/hubot-mock-adapter) is what we use for testing our own hubot, and found it really useful, so that'd be better example to include.

I opened this mainly so I could close https://github.com/hubot-scripts/hubot-example/issues/3 and https://github.com/hubot-scripts/hubot-example/issues/5

**Comment by michaelansel** [comment]
I've been thinking about testing patterns as part of #873. I think tweaking the script interface will make testing significantly easier. I'll try to write up more details on it the next time I swap that thread into working memory.

**Comment by technicalpickles** [comment]
I included an example of a script with test I wrote recently on https://github.com/github/hubot/issues/985:

https://gist.github.com/technicalpickles/971b40520fb8db63a6f4

**Comment by technicalpickles** [comment]
This was done in https://github.com/github/generator-hubot/pull/61
