### ISSUE TITLE
Hubot installation 

### ISSUE THREAD

**Issue by sarathsps0327** [github/generator-hubot#54]
I am trying to install hubot in one of my RHEL 6.0 server (after installing npm and node.js)  which is behind the company’s firewall and not exposed to internet.

I am getting this error. Is there any way to install generator-hubot by downloading the required file instead looking at the internet server registry.npmjs.org.

npm install -g yo generator-hubot 

npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "/tmp/chatOps_POC/node-v4.0.0-linux-x64/bin/node" "/tmp/chatOps_POC/node-v4.0.0-linux-x64/bin/npm" "install" "-g" "yo"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/chatOps_POC/hubot/aemhubot/npm-debug.log

**Comment by bkeepers** [comment]
You could theoretically download all the packages manually, but hubot-generator uses [yeoman](http://yeoman.io/), which has a _lot_ of dependencies. Below is the output for the dependencies listed when I run `npm install -g yo generator-hubot`.

If you're using NPM a lot behind the firewall, you might want to check out their [on-site install](https://www.npmjs.com/onsite).

```
generator-hubot@0.3.1 /opt/nodes/0.12.0/lib/node_modules/generator-hubot
├── chalk@0.5.1 (escape-string-regexp@1.0.3, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── yosay@0.3.0 (ansi-regex@0.2.1, string-length@0.1.2, ansi-styles@1.1.0, pad-component@0.0.1, word-wrap@0.1.3, strip-ansi@0.2.2, minimist@0.2.0, chalk@0.4.0, taketalk@0.1.1)
├── npm-name@1.1.1 (log-symbols@1.0.2, meow@3.3.0, registry-url@3.0.3, got@3.3.1)
└── yeoman-generator@0.17.7 (dargs@2.1.0, isbinaryfile@2.0.4, class-extend@0.1.1, diff@1.4.0, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.2, cross-spawn@0.2.9, grouped-queue@0.3.0, nopt@3.0.4, debug@1.0.4, mkdirp@0.5.1, run-async@0.1.0, shelljs@0.3.0, iconv-lite@0.4.11, github-username@1.1.1, rimraf@2.4.3, glob@4.5.3, file-utils@0.2.2, findup-sync@0.1.3, lodash@2.4.2, gruntfile-editor@0.2.0, cheerio@0.17.0, download@1.0.7, request@2.62.0, inquirer@0.7.3)

yo@1.4.8 /opt/nodes/0.12.0/lib/node_modules/yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.4.0
├── async@1.4.2
├── humanize-string@1.0.1 (decamelize@1.0.0)
├── yeoman-character@1.0.1 (supports-color@1.3.1)
├── user-home@2.0.0 (os-homedir@1.0.1)
├── opn@3.0.2 (object-assign@3.0.0)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── sort-on@1.2.2 (arrify@1.0.0, dot-prop@2.2.0)
├── repeating@1.1.3 (is-finite@1.0.1)
├── root-check@1.0.0 (sudo-block@1.2.0, downgrade-root@1.1.0)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── meow@3.3.0 (object-assign@3.0.0, indent-string@1.2.2, camelcase-keys@1.0.0, minimist@1.2.0)
├── yosay@1.0.5 (ansi-regex@1.1.1, ansi-styles@2.1.0, strip-ansi@2.0.1, word-wrap@1.1.0, pad-component@0.0.1, taketalk@1.0.0, minimist@1.2.0, string-width@1.0.1)
├── configstore@1.2.1 (os-tmpdir@1.0.1, object-assign@3.0.0, graceful-fs@4.1.2, xdg-basedir@2.0.0, osenv@0.1.3, uuid@2.0.1, write-file-atomic@1.1.3, mkdirp@0.5.1)
├── update-notifier@0.5.0 (is-npm@1.0.0, latest-version@1.0.1, semver-diff@2.0.0)
├── got@4.2.0 (lowercase-keys@1.0.0, timed-out@2.0.0, is-stream@1.0.1, is-redirect@1.0.0, prepend-http@1.0.3, object-assign@3.0.0, is-plain-obj@1.0.0, unzip-response@1.0.0, node-status-codes@1.0.0, pinkie-promise@1.0.0, create-error-class@2.0.1, parse-json@2.2.0, duplexify@3.4.2, read-all-stream@3.0.1)
├── npm-keyword@1.2.0 (registry-url@3.0.3, got@3.3.1)
├── package-json@1.2.0 (registry-url@3.0.3, got@3.3.1)
├── fullname@1.1.1 (npmconf@2.1.2)
├── cross-spawn@0.4.1 (lru-cache@2.7.0, spawn-sync@1.0.13)
├── inquirer@0.9.0 (strip-ansi@3.0.0, ansi-regex@2.0.0, cli-width@1.0.1, through@2.3.8, readline2@0.1.1, run-async@0.1.0, rx-lite@2.5.2)
├── lodash@3.10.1
├── yeoman-doctor@1.4.0 (object-values@1.0.0, log-symbols@1.0.2, user-home@1.1.1, each-async@1.1.1, semver@4.3.6, bin-version-check@2.1.0, twig@0.8.2)
├── insight@0.6.0 (object-assign@2.1.1, lodash.debounce@3.1.1, async@0.9.2, os-name@1.0.3, tough-cookie@1.2.0, request@2.62.0, inquirer@0.8.5)
└── yeoman-environment@1.2.7 (log-symbols@1.0.2, escape-string-regexp@1.0.3, diff@1.4.0, untildify@2.1.0, text-table@0.2.0, debug@2.2.0, mem-fs@1.1.0, globby@2.1.0, grouped-queue@0.3.0, inquirer@0.8.5)
```

**Comment by sarathsps0327** [comment]
Thank you very much for your comments.
The server is behind corporate firewall and we don't have any option other than downloading all the packages.
if I install the onsite npm will it covers all the modules you have listed above (including the hubot generator and yeoman)?
 
Thanks, Partha

**Comment by bkeepers** [comment]
> if I install the onsite npm will it covers all the modules you have listed above (including the hubot generator and yeoman)?

I haven't actually used npm onsite, but my understanding is that it allows your company to configure which packages are allowed and makes them available inside the firewall.

**Comment by sarathsps0327** [comment]
Hi Support team.

Thank you for your reply.

I am trying the install the onsite version of npm using the below command as mentioned the npm site 
https://docs.npmjs.com/enterprise/installation#requirements. Still it is trying to download from the internet. Is there any tar file which is available for download? How can I achieve an onsite version without looking at the packages available over internet?

$ ./npm install npme
npm ERR! Linux 2.6.18-398.el5
npm ERR! argv "/logs/installables/nodejs/node-v4.0.0-linux-x64/bin/node" "/logs/installables/nodejs/node-v4.0.0-linux-x64/bin/npm" "install" "npme"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by bkeepers** [comment]
You'll need to contact npm support for questions about npm: https://www.npmjs.com/support.

Let us know if you have any other questions about hubot.
