### ISSUE TITLE
Consider not using CoffeeScript

### ISSUE THREAD

**Issue by strugee** [github/generator-hubot#86]
CoffeeScript has kinda fallen out of vogue since Hubot was written. It makes debugging more challenging and plain JavaScript is waaaay more usable nowadays, making CoffeeScript much less compelling.

Perhaps this generator should stop generating modules and Hubots that use CoffeeScript.

**Comment by technicalpickles** [comment]
That's a good point. In fact, we have porting hubot to Javascript on our new [ROADMAP](https://github.com/github/hubot/blob/master/ROADMAP.md)

I'm going to close for now, but this will be revisited when we get closer to a release there.
